#!/bin/sh

RUN_MODE=$1
MODEL_NAME=$2
EXPERIMENT_NAME=$4
DATASET_PATH=$5
DATASET_NAME=$3

for id in 1 2 3 4 5
do
    bash run.sh $RUN_MODE $MODEL_NAME $DATASET_NAME $id $EXPERIMENT_NAME $DATASET_PATH
done
